# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release Go project

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Use Docker to build the project inside a Debian Buster container (glibc 2.28)
      - name: Build in Debian Buster (glibc 2.28) with go build
        run: |
          docker run --rm -v $(pwd):/app -w /app debian:buster /bin/bash -c "
            apt-get update && \
            apt-get install -y wget gcc make git && \
            wget https://go.dev/dl/go1.20.7.linux-amd64.tar.gz && \
            tar -C /usr/local -xzf go1.20.7.linux-amd64.tar.gz && \
            export PATH=/usr/local/go/bin:$PATH && \
            go version && \
            cd /app && \
            go mod tidy && \
            go build -v ./... && \
            rm go1.20.7.linux-amd64.tar.gz  # Clean up after build
          "

      # Add a git clean step before GoReleaser to ensure a clean state
      - name: Clean up Git State
        run: git clean -fdX

      # Run GoReleaser to handle the release process
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
